### ISSUE TITLE
No longer compatible with axum 0.6.1 due to axum core version mismatch (0.2.9 vs 0.3.0)

### ISSUE THREAD

**Issue by kraigher** [davidpdrsn/axum-tungstenite#5]
The Cargo.toml of this project might be unecessarily specific which will cause this problem also in the future.

**Comment by davidpdrsn** [comment]
I just need to update tungstenite (https://github.com/davidpdrsn/axum-tungstenite/pull/4) and axum and ship a new breaking release. Just haven't done that yet.

**Comment by kraigher** [comment]
👍

**Comment by davidpdrsn** [comment]
0.2.0 is out 🎉
